# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0002_auto_20160301_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularaccount',
            name='profile',
            field=models.TextField(default='User Profile'),
        ),
        migrations.AddField(
            model_name='regularaccount',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 1, 6, 43, 22, 836524, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traineraccount',
            name='profile',
            field=models.TextField(default='User Profile'),
        ),
        migrations.AddField(
            model_name='traineraccount',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 1, 6, 43, 32, 675599, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
